name: Build macOS DMG

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-dmg:
    runs-on: macos-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission to Gradle
        run: chmod +x gradlew

      - name: Build jar
        run: ./gradlew jar

      - name: Package DMG
        run: ./gradlew packageApp

      - name: Upload DMG artifact
        uses: actions/upload-artifact@v4
        with:
          name: BlackOut-macOS-DMG
          path: build/jpackage/*.dmg